stages:
  - build
  - deploy
  
image: golang:1.7.4-alpine

compile-go:
  stage: build
  script:
    - apk add --no-cache git
    - cd /builds/design4pro/rancher-docker-gen
    - go get github.com/Sirupsen/logrus
    - go get github.com/BurntSushi/toml
    - go get github.com/rancher/go-rancher-metadata/metadata
    - go build -ldflags "-X 'main.Version=RAP Edition $CI_BUILD_REF_NAME' -X main.GitSHA=$CI_BUILD_REF"
    - ./rancher-docker-gen  --version
    - mv rancher-docker-gen rancher-gen
  artifacts:
    paths:
    - "rancher-gen"
    name: "rancher-docker-gen"
    
rebuild-rap:
    stage: deploy
    script:
        - apk add --no-cache curl
        - curl -X POST -F token=$TOKEN_RAP -F ref=$CI_BUILD_REF_NAME https://gitlab.com/api/v3/projects/4447907/trigger/builds
